### ISSUE TITLE
callbacks version?

### ISSUE THREAD

**Issue by LittleMonster104** [panruotong/CAG#1]
Hi, when I tried to run the demo.py, I got below error:

from callbacks import Iteratorize, Stream
ImportError: cannot import name 'Iteratorize' from 'callbacks' (/opt/anaconda3/envs/CAG/lib/python3.9/site-packages/callbacks/__init__.py)

Can you please clarify?

Cheers

**Comment by panruotong** [comment]
Hello, callbacks.py is our local file which has now been uploaded. Please uninstall your original callbacks library and run it again.
