### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by chenjw505** [panruotong/CAG#2]
线上推理的时候，召回的内容是如何跟实时的query打上high，middle，low 三种 credibility 的呢？  还是说离线把所有document都打标好了？

**Comment by panruotong** [comment]
目前，我们是在离线状态下标注了文档的可信度。如果是实时标注，可以根据与查询的相似度分数、时间戳以及文档来源较快地确定可信度。

- 根据相似度分数将其按照等频率/等间隔地将文档分成三个等级。
- 计算查询提出时间与文档发布时间的差值，每超过一个时间窗口，可信度等级下降一个等级
- 将这个等级与文档来源的可靠性等级取一个最低值，作为最终的可信度。

这个可信度评估机制是灵活的，可以在这个基础上修改评估方法。之后我们也会考虑推广到在线的场景，目前没有找到这部分的合适的数据
